=== marcpawl/Triumph_TTS/fake_meshwesh/json_schemas/associatedArmyLists.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "associatedArmyLists",
  "description": "Meshwesh associatedArmyLists",
  "$id": "https://github.com/marcpawl/Triumph_TTS.git/$associatedArmyLists",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "keywords": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "derivedData": {
        "type": "object",
        "properties": {
          "listStartDate": {
            "type": "integer"
          },
          "listEndDate": {
            "type": "integer"
          },
          "extendedName": {
            "type": "string"
          }
        },
        "required": [
          "extendedName",
          "listEndDate",
          "listStartDate"
        ]
      },
      "sortId": {
        "type": "number"
      },
      "sublistId": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "invasionRatings": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "value": {
              "type": "integer"
            },
            "note": {
              "type": [
                "null",
                "string"
              ]
            }
          },
          "required": [
            "_id",
            "note",
            "value"
          ]
        }
      },
      "maneuverRatings": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "value": {
              "type": "integer"
            },
            "note": {
              "type": [
                "null",
                "string"
              ]
            }
          },
          "required": [
            "_id",
            "note",
            "value"
          ]
        }
      },
      "homeTopographies": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "values": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "_id": {
              "type": "string"
            },
            "note": {
              "type": "string"
            }
          },
          "required": [
            "_id",
            "note",
            "values"
          ]
        }
      },
      "listId": {
        "type": "number"
      },
      "dateRanges": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "startDate": {
              "type": "integer"
            },
            "endDate": {
              "type": "integer"
            }
          },
          "required": [
            "_id",
            "endDate",
            "startDate"
          ]
        }
      },
      "troopOptions": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "min": {
              "type": "integer"
            },
            "max": {
              "type": "integer"
            },
            "dateRanges": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "_id": {
                    "type": "string"
                  },
                  "startDate": {
                    "type": "integer"
                  },
                  "endDate": {
                    "type": "integer"
                  }
                },
                "required": [
                  "_id",
                  "endDate",
                  "startDate"
                ]
              }
            },
            "troopEntries": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "_id": {
                    "type": "string"
                  },
                  "troopTypeCode": {
                    "type": "string"
                  },
                  "dismountTypeCode": {
                    "type": "null"
                  },
                  "note": {
                    "type": [
                      "null",
                      "string"
                    ]
                  }
                },
                "required": [
                  "_id",
                  "dismountTypeCode",
                  "note",
                  "troopTypeCode"
                ]
              }
            },
            "description": {
              "type": "string"
            },
            "note": {
              "type": "string"
            },
            "core": {
              "type": "string"
            },
            "battleCardEntries": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "_id": {
                    "type": "string"
                  },
                  "min": {
                    "type": [
                      "integer",
                      "null"
                    ]
                  },
                  "max": {
                    "type": [
                      "integer",
                      "null"
                    ]
                  },
                  "battleCardCode": {
                    "type": "string"
                  },
                  "note": {
                    "type": [
                      "null",
                      "string"
                    ]
                  }
                },
                "required": [
                  "_id",
                  "battleCardCode",
                  "max",
                  "min",
                  "note"
                ]
              }
            }
          },
          "required": [
            "_id",
            "battleCardEntries",
            "core",
            "dateRanges",
            "description",
            "max",
            "min",
            "note",
            "troopEntries"
          ]
        }
      },
      "troopEntriesForGeneral": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "troopEntries": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "_id": {
                    "type": "string"
                  },
                  "troopTypeCode": {
                    "type": "string"
                  },
                  "dismountTypeCode": {
                    "type": "null"
                  },
                  "note": {
                    "type": [
                      "null",
                      "string"
                    ]
                  }
                },
                "required": [
                  "_id",
                  "dismountTypeCode",
                  "note",
                  "troopTypeCode"
                ]
              }
            }
          },
          "required": [
            "_id",
            "troopEntries"
          ]
        }
      },
      "allyOptions": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "dateRange": {
              "anyOf": [
                {
                  "type": "null"
                },
                {
                  "type": "object",
                  "properties": {
                    "_id": {
                      "type": "string"
                    },
                    "startDate": {
                      "type": "integer"
                    },
                    "endDate": {
                      "type": "integer"
                    }
                  },
                  "required": [
                    "_id",
                    "endDate",
                    "startDate"
                  ]
                }
              ]
            },
            "note": {
              "type": "null"
            },
            "allyEntries": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "_id": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "allyArmyList": {
                    "type": "string"
                  }
                },
                "required": [
                  "_id",
                  "allyArmyList",
                  "name"
                ]
              }
            }
          },
          "required": [
            "_id",
            "allyEntries",
            "dateRange",
            "note"
          ]
        }
      },
      "battleCardEntries": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "min": {
              "type": [
                "integer",
                "null"
              ]
            },
            "max": {
              "type": [
                "integer",
                "null"
              ]
            },
            "battleCardCode": {
              "type": "string"
            },
            "note": {
              "type": [
                "null",
                "string"
              ]
            }
          },
          "required": [
            "_id",
            "battleCardCode",
            "note"
          ]
        }
      },
      "showTroopOptionDescriptions": {
        "type": "boolean"
      },
      "status": {
        "type": "string"
      },
      "id": {
        "type": "string"
      }
    },
    "required": [
      "allyOptions",
      "battleCardEntries",
      "dateRanges",
      "derivedData",
      "homeTopographies",
      "id",
      "invasionRatings",
      "keywords",
      "listId",
      "maneuverRatings",
      "name",
      "showTroopOptionDescriptions",
      "sortId",
      "status",
      "sublistId",
      "troopEntriesForGeneral",
      "troopOptions"
    ]
  }
}

=== marcpawl/Triumph_TTS/fake_meshwesh/armyLists/5fb1b9d8e1af0600177092b3.enemyArmy.json
[{"keywords":[],"derivedData":{"listStartDate":-3000,"listEndDate":-2800,"extendedName":"Early Sumerian  3000 to 2800 BC"},"sortId":1,"sublistId":"a","name":"Early Sumerian","invasionRatings":[{"_id":"6153507203385c0016b81556","value":2,"note":null}],"maneuverRatings":[{"_id":"6153507203385c0016b81557","value":2,"note":null}],"homeTopographies":[{"values":["Delta"],"_id":"6153507203385c0016b81558","note":""}],"listId":1,"dateRanges":[{"_id":"6153507203385c0016b81559","startDate":-3000,"endDate":-2800}],"troopOptions":[{"_id":"6153519e03385c0016b84d91","min":1,"max":1,"dateRanges":[],"troopEntries":[{"_id":"6153519e03385c0016b84d92","troopTypeCode":"RDR","dismountTypeCode":null,"note":null}],"description":"Close-fighters","note":"","core":"all","battleCardEntries":[]},{"_id":"6153519e03385c0016b84d93","min":8,"max":20,"dateRanges":[],"troopEntries":[{"_id":"6153519e03385c0016b84d94","troopTypeCode":"BLV","dismountTypeCode":null,"note":null}],"description":"Household and militia bowmen","note":"","core":"","battleCardEntries":[]},{"_id":"6153519e03385c0016b84d95","min":1,"max":2,"dateRanges":[],"troopEntries":[{"_id":"6153519e03385c0016b84d96","troopTypeCode":"RBL","dismountTypeCode":null,"note":null}],"description":"Nomadic and levy javelinmen","note":"","core":"","battleCardEntries":[]},{"_id":"6153519e03385c0016b84d97","min":1,"max":6,"dateRanges":[],"troopEntries":[{"_id":"6153519e03385c0016b84d98","troopTypeCode":"SKM","dismountTypeCode":null,"note":null}],"description":"Nomadic and levy slingers and skirmishing bowmen","note":"","core":"","battleCardEntries":[]}],"troopEntriesForGeneral":[{"_id":"6153519e03385c0016b84d99","troopEntries":[{"_id":"6153519e03385c0016b84d9a","troopTypeCode":"RDR","dismountTypeCode":null,"note":null}]}],"allyOptions":[{"_id":"6153519e03385c0016b84d9b","dateRange":null,"note":null,"allyEntries":[{"_id":"6153519e03385c0016b84d9c","name":"Dry steppe nomad allies","allyArmyList":"6153518d03385c0016b834e1"}]},{"_id":"6153519e03385c0016b84d9d","dateRange":null,"note":null,"allyEntries":[{"_id":"6153519e03385c0016b84d9e","name":"Zagros Highlander allies","allyArmyList":"6153518d03385c0016b83529"}]},{"_id":"6153519e03385c0016b84d9f","dateRange":null,"note":null,"allyEntries":[{"_id":"6153519e03385c0016b84da0","name":"Elamite allies or vassals","allyArmyList":"6153518d03385c0016b834fa"}]}],"battleCardEntries":[{"_id":"6153519e03385c0016b84da1","min":null,"max":null,"battleCardCode":"PT","note":"pack donkeys"}],"showTroopOptionDescriptions":true,"status":"Revised","id":"5fb1b9d8e1af0600177092b3"},{"keywords":["Arab","Aramaean"],"derivedData":{"listStartDate":-3000,"listEndDate":-2001,"extendedName":"Nomadic Amurru  3000 to 2001 BC"},"sortId":7,"sublistId":"a","name":"Nomadic Amurru","invasionRatings":[{"_id":"6153507203385c0016b8158f","value":3,"note":null}],"maneuverRatings":[{"_id":"6153507203385c0016b81590","value":0,"note":null}],"homeTopographies":[{"values":["Dry"],"_id":"6153507203385c0016b81591","note":""}],"listId":7,"dateRanges":[{"_id":"6153507203385c0016b81592","startDate":-3000,"endDate":-2001}],"troopOptions":[{"_id":"6153519e03385c0016b84e8b","min":1,"max":6,"dateRanges":[],"troopEntries":[{"_id":"6153519e03385c0016b84e8c","troopTypeCode":"LFT","dismountTypeCode":null,"note":null}],"description":"Retainers and effective javelinmen","note":"","core":"all","battleCardEntries":[]},{"_id":"6153519e03385c0016b84e8d","min":6,"max":20,"dateRanges":[],"troopEntries":[{"_id":"6153519e03385c0016b84e8e","troopTypeCode":"RBL","dismountTypeCode":null,"note":null}],"description":"Unshielded javelinmen","note":"","core":"","battleCardEntries":[]},{"_id":"6153519e03385c0016b84e8f","min":1,"max":3,"dateRanges":[],"troopEntries":[{"_id":"6153519e03385c0016b84e90","troopTypeCode":"SKM","dismountTypeCode":null,"note":null}],"description":"Slingers","note":"","core":"","battleCardEntries":[]},{"_id":"6153519e03385c0016b84e91","min":1,"max":3,"dateRanges":[],"troopEntries":[{"_id":"6153519e03385c0016b84e92","troopTypeCode":"BLV","dismountTypeCode":null,"note":null},{"_id":"6153519e03385c0016b84e93","troopTypeCode":"ARC","dismountTypeCode":null,"note":null}],"description":"Bowmen","note":"","core":"all","battleCardEntries":[]}],"troopEntriesForGeneral":[{"_id":"6153519e03385c0016b84e94","troopEntries":[{"_id":"6153519e03385c0016b84e95","troopTypeCode":"LFT","dismountTypeCode":null,"note":null}]}],"allyOptions":[{"_id":"6153519e03385c0016b84e96","dateRange":{"_id":"6153519e03385c0016b84e97","startDate":-2200,"endDate":-2001},"note":null,"allyEntries":[{"_id":"6153519e03385c0016b84e98","name":"Subject Syrian city allies: Note! Going beyond end date of Early Syrian is deliberate","allyArmyList":"6153518d03385c0016b83535"}]},{"_id":"6153519e03385c0016b84e99","dateRange":{"_id":"6153519e03385c0016b84e9a","startDate":-2025,"endDate":-2001},"note":null,"allyEntries":[{"_id":"6153519e03385c0016b84e9b","name":"Subject Mesopotamian city allies","allyArmyList":"6153518d03385c0016b834d0"}]},{"_id":"6153519e03385c0016b84e9c","dateRange":{"_id":"6153519e03385c0016b84e9d","startDate":-2025,"endDate":-2001},"note":null,"allyEntries":[{"_id":"6153519e03385c0016b84e9e","name":"Subject Mesopotamian city allies","allyArmyList":"6153518d03385c0016b834c1"}]}],"battleCardEntries":[{"_id":"6153519e03385c0016b84e9f","min":null,"max":null,"battleCardCode":"PT","note":"pack donkeys"}],"showTroopOptionDescriptions":true,"status":"Revised","id":"5fb1b9d8e1af0600177092ec"},{"keywords":[],"derivedData":{"listStartDate":-3000,"listEndDate":-2601,"extendedName":"Proto-Elamite  3000 to 2601 BC"},"sortId":8,"sublistId":"a","name":"Proto-Elamite","invasionRatings":[{"_id":"6153507203385c0016b8159d","value":3,"note":null}],"maneuverRatings":[{"_id":"6153507203385c0016b8159e","value":0,"note":null}],"homeTopographies":[{"values":["Dry"],"_id":"6153507203385c0016b8159f","note":""}],"listId":8,"dateRanges":[{"_id":"6153507203385c0016b815a0","startDate":-3000,"endDate":-2601}],"troopOptions":[{"_id":"6153519e03385c0016b84ebb","min":1,"max":1,"dateRanges":[],"troopEntries":[{"_id":"6153519e03385c0016b84ebc","troopTypeCode":"ARC","dismountTypeCode":null,"note":null}],"description":"Retainers","note":"","core":"all","battleCardEntries":[]},{"_id":"6153519e03385c0016b84ebd","min":16,"max":22,"dateRanges":[],"troopEntries":[{"_id":"6153519e03385c0016b84ebe","troopTypeCode":"BLV","dismountTypeCode":null,"note":null}],"description":"Bowmen","note":"","core":"","battleCardEntries":[]}],"troopEntriesForGeneral":[{"_id":"6153519e03385c0016b84ebf","troopEntries":[{"_id":"6153519e03385c0016b84ec0","troopTypeCode":"ARC","dismountTypeCode":null,"note":null}]}],"allyOptions":[{"_id":"6153519e03385c0016b84ec1","dateRange":null,"note":null,"allyEntries":[{"_id":"6153519e03385c0016b84ec2","name":"Zagros Highlander allies","allyArmyList":"6153518d03385c0016b83529"}]}],"battleCardEntries":[{"_id":"6153519e03385c0016b84ec3","min":null,"max":null,"battleCardCode":"PT","note":"pack donkeys"}],"showTroopOptionDescriptions":true,"status":"Revised","id":"5fb1b9d8e1af0600177092fa"},{"keywords":["Anatolian","Highland"],"derivedData":{"listStartDate":-3000,"listEndDate":-950,"extendedName":"Early Bronze Age Highlanders  3000 to 950 BC"},"sortId":9,"sublistId":"e","name":"Early Bronze Age Highlanders","invasionRatings":[{"_id":"6153507203385c0016b815ca","value":3,"note":null}],"maneuverRatings":[{"_id":"6153507203385c0016b815cb","value":1,"note":null}],"homeTopographies":[{"values":["Hilly"],"_id":"6153507203385c0016b815cc","note":""}],"listId":9,"dateRanges":[{"_id":"6153507203385c0016b815cd","startDate":-3000,"endDate":-950}],"troopOptions":[{"_id":"6153519e03385c0016b84f52","min":1,"max":2,"dateRanges":[],"troopEntries":[{"_id":"6153519e03385c0016b84f53","troopTypeCode":"RDR","dismountTypeCode":null,"note":null},{"_id":"6153519e03385c0016b84f54","troopTypeCode":"ARC","dismountTypeCode":null,"note":null}],"description":"Bodyguards","note":"","core":"all","battleCardEntries":[]},{"_id":"6153519e03385c0016b84f55","min":8,"max":20,"dateRanges":[],"troopEntries":[{"_id":"6153519e03385c0016b84f56","troopTypeCode":"RBL","dismountTypeCode":null,"note":null}],"description":"Unshielded javelinmen","note":"","core":"","battleCardEntries":[]},{"_id":"6153519e03385c0016b84f57","min":0,"max":3,"dateRanges":[{"_id":"6153519e03385c0016b84f58","startDate":-1500,"endDate":-950}],"troopEntries":[{"_id":"6153519e03385c0016b84f59","troopTypeCode":"LFT","dismountTypeCode":null,"note":null}],"description":"Javelinmen with shields","note":"","core":"all","battleCardEntries":[]},{"_id":"6153519e03385c0016b84f5a","min":4,"max":12,"dateRanges":[],"troopEntries":[{"_id":"6153519e03385c0016b84f5b","troopTypeCode":"BLV","dismountTypeCode":null,"note":null}],"description":"Bowmen","note":"","core":"","battleCardEntries":[]},{"_id":"6153519e03385c0016b84f5c","min":0,"max":2,"dateRanges":[],"troopEntries":[{"_id":"6153519e03385c0016b84f5d","troopTypeCode":"SKM","dismountTypeCode":null,"note":null}],"description":"Slingers","note":"","core":"","battleCardEntries":[]}],"troopEntriesForGeneral":[{"_id":"6153519e03385c0016b84f5e","troopEntries":[{"_id":"6153519e03385c0016b84f5f","troopTypeCode":"RDR","dismountTypeCode":null,"note":null},{"_id":"6153519e03385c0016b84f60","troopTypeCode":"ARC","dismountTypeCode":null,"note":null}]}],"allyOptions":[],"battleCardEntries":[{"_id":"6153519e03385c0016b84f61","min":null,"max":null,"battleCardCode":"PT","note":"pack donkeys"}],"showTroopOptionDescriptions":true,"status":"Revised","id":"5fb1b9d9e1af060017709327"}]

=== marcpawl/Triumph_TTS/fake_meshwesh/armyLists/5fb1b9f5e1af06001770a38c.enemyArmy.json
[{"keywords":["American"],"derivedData":{"listStartDate":-899,"listEndDate":-400,"extendedName":"Early Nomadic Meso-American  899 to 400 BC"},"sortId":343,"sublistId":"b","name":"Early Nomadic Meso-American","invasionRatings":[{"_id":"6153508e03385c0016b82612","value":2,"note":null}],"maneuverRatings":[{"_id":"6153508e03385c0016b82613","value":2,"note":null}],"homeTopographies":[{"values":["Forest"," Hilly"],"_id":"6153508e03385c0016b82614","note":""}],"listId":911,"dateRanges":[{"_id":"6153508e03385c0016b82615","startDate":-899,"endDate":-400}],"troopOptions":[{"_id":"615351b603385c0016b88d6d","min":0,"max":2,"dateRanges":[],"troopEntries":[{"_id":"615351b603385c0016b88d6e","troopTypeCode":"LFT","dismountTypeCode":null,"note":null}],"description":"Well equipped or trained infantry","note":"","core":"all","battleCardEntries":[]},{"_id":"615351b603385c0016b88d6f","min":11,"max":16,"dateRanges":[],"troopEntries":[{"_id":"615351b603385c0016b88d70","troopTypeCode":"SKM","dismountTypeCode":null,"note":null}],"description":"Hit-and-run unshielded fighters armed with substantial melee weapons","note":"","core":"","battleCardEntries":[]},{"_id":"615351b603385c0016b88d71","min":0,"max":4,"dateRanges":[],"troopEntries":[{"_id":"615351b603385c0016b88d72","troopTypeCode":"RBL","dismountTypeCode":null,"note":null}],"description":"Poorly-armed skirmishing foot","note":"","core":"","battleCardEntries":[]}],"troopEntriesForGeneral":[{"_id":"615351b603385c0016b88d73","troopEntries":[{"_id":"615351b603385c0016b88d74","troopTypeCode":"LFT","dismountTypeCode":null,"note":null}]},{"_id":"615351b603385c0016b88d75","troopEntries":[{"_id":"615351b603385c0016b88d76","troopTypeCode":"RBL","dismountTypeCode":null,"note":null}]}],"allyOptions":[],"battleCardEntries":[],"showTroopOptionDescriptions":true,"status":"Revised","id":"5fb1b9f5e1af06001770a38c"},{"keywords":["American"],"derivedData":{"listStartDate":-600,"listEndDate":950,"extendedName":"Minor Mexican City-States  600 BC to 950 AD"},"sortId":344,"sublistId":"a","name":"Minor Mexican City-States","invasionRatings":[{"_id":"6153508e03385c0016b82619","value":1,"note":null}],"maneuverRatings":[{"_id":"6153508e03385c0016b8261a","value":0,"note":null}],"homeTopographies":[{"values":["Hilly"],"_id":"6153508e03385c0016b8261b","note":""}],"listId":912,"dateRanges":[{"_id":"6153508e03385c0016b8261c","startDate":-600,"endDate":950}],"troopOptions":[{"_id":"615351b603385c0016b88d77","min":8,"max":16,"dateRanges":[],"troopEntries":[{"_id":"615351b603385c0016b88d78","troopTypeCode":"HFT","dismountTypeCode":null,"note":null}],"description":"Nobles armed with long spears and large shields","note":"","core":"all","battleCardEntries":[]},{"_id":"615351b603385c0016b88d79","min":0,"max":6,"dateRanges":[],"troopEntries":[{"_id":"615351b603385c0016b88d7a","troopTypeCode":"HRD","dismountTypeCode":null,"note":null}],"description":"Poorly-armed commoners","note":"","core":"","battleCardEntries":[]},{"_id":"615351b603385c0016b88d7b","min":0,"max":4,"dateRanges":[],"troopEntries":[{"_id":"615351b603385c0016b88d7c","troopTypeCode":"SKM","dismountTypeCode":null,"note":null}],"description":"Peasant skirmishing slingers","note":"","core":"","battleCardEntries":[]}],"troopEntriesForGeneral":[{"_id":"615351b603385c0016b88d7d","troopEntries":[{"_id":"615351b603385c0016b88d7e","troopTypeCode":"HFT","dismountTypeCode":null,"note":null}]}],"allyOptions":[],"battleCardEntries":[],"showTroopOptionDescriptions":true,"status":"Revised","id":"5fb1b9f5e1af06001770a393"},{"keywords":["American"],"derivedData":{"listStartDate":-500,"listEndDate":1100,"extendedName":"Oaxaca  500 BC to 1100 AD"},"sortId":345,"sublistId":"a","name":"Oaxaca","invasionRatings":[{"_id":"6153508e03385c0016b82620","value":2,"note":null}],"maneuverRatings":[{"_id":"6153508e03385c0016b82621","value":2,"note":"1 BC-200 AD"},{"_id":"6153508e03385c0016b82622","value":0,"note":"651-1100 AD"},{"_id":"6153508e03385c0016b82623","value":1,"note":"Otherwise"}],"homeTopographies":[{"values":["Hilly"],"_id":"6153508e03385c0016b82624","note":""}],"listId":913,"dateRanges":[{"_id":"6153508e03385c0016b82625","startDate":-500,"endDate":1100}],"troopOptions":[{"_id":"615351b603385c0016b88d7f","min":8,"max":16,"dateRanges":[],"troopEntries":[{"_id":"615351b603385c0016b88d80","troopTypeCode":"LSP","dismountTypeCode":null,"note":null}],"description":"Nobles armed with long spears and clubs or small shields","note":"","core":"all","battleCardEntries":[]},{"_id":"615351b603385c0016b88d81","min":0,"max":2,"dateRanges":[],"troopEntries":[{"_id":"615351b603385c0016b88d82","troopTypeCode":"RDR","dismountTypeCode":null,"note":null}],"description":"Suit-wearers armed with long spears and clubs or small shields","note":"","core":"","battleCardEntries":[]},{"_id":"615351b603385c0016b88d83","min":0,"max":2,"dateRanges":[],"troopEntries":[{"_id":"615351b603385c0016b88d84","troopTypeCode":"LFT","dismountTypeCode":null,"note":null}],"description":"Garrison troops armed with mixed weapons","note":"","core":"","battleCardEntries":[]},{"_id":"615351b603385c0016b88d85","min":0,"max":6,"dateRanges":[],"troopEntries":[{"_id":"615351b603385c0016b88d86","troopTypeCode":"HRD","dismountTypeCode":null,"note":null}],"description":"Poorly-armed commoners","note":"","core":"","battleCardEntries":[]},{"_id":"615351b603385c0016b88d87","min":0,"max":4,"dateRanges":[],"troopEntries":[{"_id":"615351b603385c0016b88d88","troopTypeCode":"SKM","dismountTypeCode":null,"note":null}],"description":"Peasant skirmishing slingers","note":"","core":"","battleCardEntries":[]}],"troopEntriesForGeneral":[{"_id":"615351b603385c0016b88d89","troopEntries":[{"_id":"615351b603385c0016b88d8a","troopTypeCode":"LSP","dismountTypeCode":null,"note":null}]}],"allyOptions":[],"battleCardEntries":[],"showTroopOptionDescriptions":true,"status":"Revised","id":"5fb1b9f5e1af06001770a39a"},{"keywords":["American"],"derivedData":{"listStartDate":-1150,"listEndDate":-400,"extendedName":"Olmec  1150 to 400 BC"},"sortId":342,"sublistId":"a","name":"Olmec","invasionRatings":[{"_id":"6153508e03385c0016b82604","value":4,"note":null}],"maneuverRatings":[{"_id":"6153508e03385c0016b82605","value":1,"note":null}],"homeTopographies":[{"values":["Forest"],"_id":"6153508e03385c0016b82606","note":""}],"listId":910,"dateRanges":[{"_id":"6153508e03385c0016b82607","startDate":-1150,"endDate":-400}],"troopOptions":[{"_id":"615351b603385c0016b88d5c","min":0,"max":2,"dateRanges":[],"troopEntries":[{"_id":"615351b603385c0016b88d5d","troopTypeCode":"HFT","dismountTypeCode":null,"note":null}],"description":"Warrior societies","note":"","core":"all","battleCardEntries":[]},{"_id":"615351b603385c0016b88d5e","min":8,"max":16,"dateRanges":[],"troopEntries":[{"_id":"615351b603385c0016b88d5f","troopTypeCode":"HFT","dismountTypeCode":null,"note":null}],"description":"Fighters armed with spears and clubs","note":"","core":"","battleCardEntries":[]},{"_id":"615351b603385c0016b88d60","min":2,"max":6,"dateRanges":[{"_id":"615351b603385c0016b88d61","startDate":-899,"endDate":-400}],"troopEntries":[{"_id":"615351b603385c0016b88d62","troopTypeCode":"SKM","dismountTypeCode":null,"note":null}],"description":"Skirmishing slingers","note":"","core":"","battleCardEntries":[]}],"troopEntriesForGeneral":[{"_id":"615351b603385c0016b88d63","troopEntries":[{"_id":"615351b603385c0016b88d64","troopTypeCode":"HFT","dismountTypeCode":null,"note":null}]}],"allyOptions":[],"battleCardEntries":[],"showTroopOptionDescriptions":true,"status":"Revised","id":"5fb1b9f4e1af06001770a37e"},{"keywords":["American"],"derivedData":{"listStartDate":-1150,"listEndDate":-400,"extendedName":"Early Settled Meso-American  1150 to 400 BC"},"sortId":343,"sublistId":"a","name":"Early Settled Meso-American","invasionRatings":[{"_id":"6153508e03385c0016b8260b","value":1,"note":null}],"maneuverRatings":[{"_id":"6153508e03385c0016b8260c","value":1,"note":null}],"homeTopographies":[{"values":["Forest"," Hilly"],"_id":"6153508e03385c0016b8260d","note":""}],"listId":911,"dateRanges":[{"_id":"6153508e03385c0016b8260e","startDate":-1150,"endDate":-400}],"troopOptions":[{"_id":"615351b603385c0016b88d65","min":0,"max":2,"dateRanges":[],"troopEntries":[{"_id":"615351b603385c0016b88d66","troopTypeCode":"LFT","dismountTypeCode":null,"note":null}],"description":"Well equipped or trained infantry","note":"","core":"all","battleCardEntries":[]},{"_id":"615351b603385c0016b88d67","min":21,"max":24,"dateRanges":[],"troopEntries":[{"_id":"615351b603385c0016b88d68","troopTypeCode":"RBL","dismountTypeCode":null,"note":null}],"description":"Untrained tribesmen and poorly armed skirmishers","note":"","core":"","battleCardEntries":[]}],"troopEntriesForGeneral":[{"_id":"615351b603385c0016b88d69","troopEntries":[{"_id":"615351b603385c0016b88d6a","troopTypeCode":"LFT","dismountTypeCode":null,"note":null}]},{"_id":"615351b603385c0016b88d6b","troopEntries":[{"_id":"615351b603385c0016b88d6c","troopTypeCode":"RBL","dismountTypeCode":null,"note":null}]}],"allyOptions":[],"battleCardEntries":[],"showTroopOptionDescriptions":true,"status":"Revised","id":"5fb1b9f5e1af06001770a385"}]
