=== marcpawl/Triumph_TTS/fake_meshwesh/json_schemas/associatedArmyLists.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "associatedArmyLists",
  "description": "Meshwesh associatedArmyLists",
  "$id": "https://github.com/marcpawl/Triumph_TTS.git/$associatedArmyLists",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "keywords": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "derivedData": {
        "type": "object",
        "properties": {
          "listStartDate": {
            "type": "integer"
          },
          "listEndDate": {
            "type": "integer"
          },
          "extendedName": {
            "type": "string"
          }
        },
        "required": [
          "extendedName",
          "listEndDate",
          "listStartDate"
        ]
      },
      "sortId": {
        "type": "number"
      },
      "sublistId": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "invasionRatings": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "value": {
              "type": "integer"
            },
            "note": {
              "type": [
                "null",
                "string"
              ]
            }
          },
          "required": [
            "_id",
            "note",
            "value"
          ]
        }
      },
      "maneuverRatings": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "value": {
              "type": "integer"
            },
            "note": {
              "type": [
                "null",
                "string"
              ]
            }
          },
          "required": [
            "_id",
            "note",
            "value"
          ]
        }
      },
      "homeTopographies": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "values": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "_id": {
              "type": "string"
            },
            "note": {
              "type": "string"
            }
          },
          "required": [
            "_id",
            "note",
            "values"
          ]
        }
      },
      "listId": {
        "type": "number"
      },
      "dateRanges": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "startDate": {
              "type": "integer"
            },
            "endDate": {
              "type": "integer"
            }
          },
          "required": [
            "_id",
            "endDate",
            "startDate"
          ]
        }
      },
      "troopOptions": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "min": {
              "type": "integer"
            },
            "max": {
              "type": "integer"
            },
            "dateRanges": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "_id": {
                    "type": "string"
                  },
                  "startDate": {
                    "type": "integer"
                  },
                  "endDate": {
                    "type": "integer"
                  }
                },
                "required": [
                  "_id",
                  "endDate",
                  "startDate"
                ]
              }
            },
            "troopEntries": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "_id": {
                    "type": "string"
                  },
                  "troopTypeCode": {
                    "type": "string"
                  },
                  "dismountTypeCode": {
                    "type": "null"
                  },
                  "note": {
                    "type": [
                      "null",
                      "string"
                    ]
                  }
                },
                "required": [
                  "_id",
                  "dismountTypeCode",
                  "note",
                  "troopTypeCode"
                ]
              }
            },
            "description": {
              "type": "string"
            },
            "note": {
              "type": "string"
            },
            "core": {
              "type": "string"
            },
            "battleCardEntries": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "_id": {
                    "type": "string"
                  },
                  "min": {
                    "type": [
                      "integer",
                      "null"
                    ]
                  },
                  "max": {
                    "type": [
                      "integer",
                      "null"
                    ]
                  },
                  "battleCardCode": {
                    "type": "string"
                  },
                  "note": {
                    "type": [
                      "null",
                      "string"
                    ]
                  }
                },
                "required": [
                  "_id",
                  "battleCardCode",
                  "max",
                  "min",
                  "note"
                ]
              }
            }
          },
          "required": [
            "_id",
            "battleCardEntries",
            "core",
            "dateRanges",
            "description",
            "max",
            "min",
            "note",
            "troopEntries"
          ]
        }
      },
      "troopEntriesForGeneral": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "troopEntries": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "_id": {
                    "type": "string"
                  },
                  "troopTypeCode": {
                    "type": "string"
                  },
                  "dismountTypeCode": {
                    "type": "null"
                  },
                  "note": {
                    "type": [
                      "null",
                      "string"
                    ]
                  }
                },
                "required": [
                  "_id",
                  "dismountTypeCode",
                  "note",
                  "troopTypeCode"
                ]
              }
            }
          },
          "required": [
            "_id",
            "troopEntries"
          ]
        }
      },
      "allyOptions": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "dateRange": {
              "anyOf": [
                {
                  "type": "null"
                },
                {
                  "type": "object",
                  "properties": {
                    "_id": {
                      "type": "string"
                    },
                    "startDate": {
                      "type": "integer"
                    },
                    "endDate": {
                      "type": "integer"
                    }
                  },
                  "required": [
                    "_id",
                    "endDate",
                    "startDate"
                  ]
                }
              ]
            },
            "note": {
              "type": "null"
            },
            "allyEntries": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "_id": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "allyArmyList": {
                    "type": "string"
                  }
                },
                "required": [
                  "_id",
                  "allyArmyList",
                  "name"
                ]
              }
            }
          },
          "required": [
            "_id",
            "allyEntries",
            "dateRange",
            "note"
          ]
        }
      },
      "battleCardEntries": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "min": {
              "type": [
                "integer",
                "null"
              ]
            },
            "max": {
              "type": [
                "integer",
                "null"
              ]
            },
            "battleCardCode": {
              "type": "string"
            },
            "note": {
              "type": [
                "null",
                "string"
              ]
            }
          },
          "required": [
            "_id",
            "battleCardCode",
            "note"
          ]
        }
      },
      "showTroopOptionDescriptions": {
        "type": "boolean"
      },
      "status": {
        "type": "string"
      },
      "id": {
        "type": "string"
      }
    },
    "required": [
      "allyOptions",
      "battleCardEntries",
      "dateRanges",
      "derivedData",
      "homeTopographies",
      "id",
      "invasionRatings",
      "keywords",
      "listId",
      "maneuverRatings",
      "name",
      "showTroopOptionDescriptions",
      "sortId",
      "status",
      "sublistId",
      "troopEntriesForGeneral",
      "troopOptions"
    ]
  }
}

=== marcpawl/Triumph_TTS/fake_meshwesh/armyLists/5fb1b9d8e1af0600177092fa.associatedArmyLists.json
[{"keywords":[],"derivedData":{"listStartDate":-2600,"listEndDate":-2101,"extendedName":"Awan Dynasty Elamite  2600 to 2101 BC"},"sortId":8,"sublistId":"b","name":"Awan Dynasty Elamite","invasionRatings":[{"_id":"6153507203385c0016b815a3","value":3,"note":null}],"maneuverRatings":[{"_id":"6153507203385c0016b815a4","value":1,"note":null}],"homeTopographies":[{"values":["Dry"],"_id":"6153507203385c0016b815a5","note":""}],"listId":8,"dateRanges":[{"_id":"6153507203385c0016b815a6","startDate":-2600,"endDate":-2101}],"troopOptions":[{"_id":"6153519e03385c0016b84ec4","min":1,"max":1,"dateRanges":[],"troopEntries":[{"_id":"6153519e03385c0016b84ec5","troopTypeCode":"ARC","dismountTypeCode":null,"note":null},{"_id":"6153519e03385c0016b84ec6","troopTypeCode":"LSP","dismountTypeCode":null,"note":null},{"_id":"6153519e03385c0016b84ec7","troopTypeCode":"RDR","dismountTypeCode":null,"note":null}],"description":"Retainers","note":"","core":"all","battleCardEntries":[]},{"_id":"6153519e03385c0016b84ec8","min":0,"max":1,"dateRanges":[],"troopEntries":[{"_id":"6153519e03385c0016b84ec9","troopTypeCode":"BTX","dismountTypeCode":null,"note":null}],"description":"4-wheeled battle platforms","note":"","core":"","battleCardEntries":[]},{"_id":"6153519e03385c0016b84eca","min":0,"max":2,"dateRanges":[],"troopEntries":[{"_id":"6153519e03385c0016b84ecb","troopTypeCode":"PIK","dismountTypeCode":null,"note":null}],"description":"Household spearmen","note":"","core":"all","battleCardEntries":[]},{"_id":"6153519e03385c0016b84ecc","min":14,"max":22,"dateRanges":[],"troopEntries":[{"_id":"6153519e03385c0016b84ecd","troopTypeCode":"BLV","dismountTypeCode":null,"note":null}],"description":"Bowmen","note":"","core":"","battleCardEntries":[]}],"troopEntriesForGeneral":[{"_id":"6153519e03385c0016b84ece","troopEntries":[{"_id":"6153519e03385c0016b84ecf","troopTypeCode":"BTX","dismountTypeCode":null,"note":null},{"_id":"6153519e03385c0016b84ed0","troopTypeCode":"ARC","dismountTypeCode":null,"note":null},{"_id":"6153519e03385c0016b84ed1","troopTypeCode":"RDR","dismountTypeCode":null,"note":null},{"_id":"6153519e03385c0016b84ed2","troopTypeCode":"LSP","dismountTypeCode":null,"note":null}]}],"allyOptions":[{"_id":"6153519e03385c0016b84ed3","dateRange":null,"note":null,"allyEntries":[{"_id":"6153519e03385c0016b84ed4","name":"Zagros Highlander allies","allyArmyList":"6153518d03385c0016b83529"}]}],"battleCardEntries":[{"_id":"6153519e03385c0016b84ed5","min":null,"max":null,"battleCardCode":"PT","note":"pack donkeys"}],"showTroopOptionDescriptions":true,"status":"Revised","id":"5fb1b9d8e1af060017709300"},{"keywords":["Elamite"],"derivedData":{"listStartDate":-2100,"listEndDate":-1401,"extendedName":"Early Elam  2100 to 1401 BC"},"sortId":8,"sublistId":"c","name":"Early Elam","invasionRatings":[{"_id":"6153507203385c0016b815a9","value":3,"note":null}],"maneuverRatings":[{"_id":"6153507203385c0016b815aa","value":1,"note":null}],"homeTopographies":[{"values":["Dry"],"_id":"6153507203385c0016b815ab","note":""}],"listId":8,"dateRanges":[{"_id":"6153507203385c0016b815ac","startDate":-2100,"endDate":-1401}],"troopOptions":[{"_id":"6153519e03385c0016b84ed6","min":1,"max":3,"dateRanges":[],"troopEntries":[{"_id":"6153519e03385c0016b84ed7","troopTypeCode":"ARC","dismountTypeCode":null,"note":null},{"_id":"6153519e03385c0016b84ed8","troopTypeCode":"RDR","dismountTypeCode":null,"note":null}],"description":"Retainers","note":"","core":"all","battleCardEntries":[]},{"_id":"6153519e03385c0016b84ed9","min":0,"max":1,"dateRanges":[],"troopEntries":[{"_id":"6153519e03385c0016b84eda","troopTypeCode":"BTX","dismountTypeCode":null,"note":null}],"description":"4-wheeled battle platforms or straddle cars","note":"","core":"all","battleCardEntries":[]},{"_id":"6153519e03385c0016b84edb","min":9,"max":22,"dateRanges":[],"troopEntries":[{"_id":"6153519e03385c0016b84edc","troopTypeCode":"BLV","dismountTypeCode":null,"note":null}],"description":"Bowmen","note":"","core":"","battleCardEntries":[]}],"troopEntriesForGeneral":[{"_id":"6153519e03385c0016b84edd","troopEntries":[{"_id":"6153519e03385c0016b84ede","troopTypeCode":"BTX","dismountTypeCode":null,"note":null},{"_id":"6153519e03385c0016b84edf","troopTypeCode":"ARC","dismountTypeCode":null,"note":null},{"_id":"6153519e03385c0016b84ee0","troopTypeCode":"RDR","dismountTypeCode":null,"note":null}]}],"allyOptions":[{"_id":"6153519e03385c0016b84ee1","dateRange":null,"note":null,"allyEntries":[{"_id":"6153519e03385c0016b84ee2","name":"Zagros Highlander allies","allyArmyList":"6153518d03385c0016b83529"}]},{"_id":"6153519e03385c0016b84ee3","dateRange":{"_id":"6153519e03385c0016b84ee4","startDate":-2100,"endDate":-1850},"note":null,"allyEntries":[{"_id":"6153519e03385c0016b84ee5","name":"Amurru allies","allyArmyList":"6153518d03385c0016b834ec"}]},{"_id":"6153519e03385c0016b84ee6","dateRange":{"_id":"6153519e03385c0016b84ee7","startDate":-2100,"endDate":-1850},"note":null,"allyEntries":[{"_id":"6153519e03385c0016b84ee8","name":"Melukhkhan allies","allyArmyList":"6153518d03385c0016b834b8"}]},{"_id":"6153519e03385c0016b84ee9","dateRange":{"_id":"6153519e03385c0016b84eea","startDate":-1769,"endDate":-1769},"note":null,"allyEntries":[{"_id":"6153519e03385c0016b84eeb","name":"Mari or Babylonian allies","allyArmyList":"6153518e03385c0016b83563"}]},{"_id":"6153519e03385c0016b84eec","dateRange":{"_id":"6153519e03385c0016b84eed","startDate":-1768,"endDate":-1768},"note":null,"allyEntries":[{"_id":"6153519e03385c0016b84eee","name":"Eshnunnan vassal allies","allyArmyList":"6153518d03385c0016b834c1"}]},{"_id":"6153519e03385c0016b84eef","dateRange":{"_id":"6153519e03385c0016b84ef0","startDate":-1764,"endDate":-1764},"note":null,"allyEntries":[{"_id":"6153519e03385c0016b84ef1","name":"Assyrian allies","allyArmyList":"6153518e03385c0016b83563"}]},{"_id":"6153519e03385c0016b84ef2","dateRange":{"_id":"6153519e03385c0016b84ef3","startDate":-1764,"endDate":-1764},"note":null,"allyEntries":[{"_id":"6153519e03385c0016b84ef4","name":"Malgi (Amurru) allies","allyArmyList":"6153518d03385c0016b834ec"}]},{"_id":"6153519e03385c0016b84ef5","dateRange":{"_id":"6153519e03385c0016b84ef6","startDate":-2100,"endDate":-1850},"note":null,"allyEntries":[{"_id":"6153519e03385c0016b84ef7","name":"Melukhkhan allies","allyArmyList":"6153518d03385c0016b834b8"},{"_id":"6153519e03385c0016b84ef8","name":"Amurru allies","allyArmyList":"6153518d03385c0016b834ec"}]}],"battleCardEntries":[{"_id":"6153519e03385c0016b84ef9","min":null,"max":null,"battleCardCode":"PT","note":"pack donkeys"}],"showTroopOptionDescriptions":true,"status":"Revised","id":"5fb1b9d8e1af060017709306"},{"keywords":["Elamite"],"derivedData":{"listStartDate":-1400,"listEndDate":-800,"extendedName":"Middle Elam  1400 to 800 BC"},"sortId":8,"sublistId":"d","name":"Middle Elam","invasionRatings":[{"_id":"6153507203385c0016b815b0","value":3,"note":null}],"maneuverRatings":[{"_id":"6153507203385c0016b815b1","value":1,"note":null}],"homeTopographies":[{"values":["Dry"],"_id":"6153507203385c0016b815b2","note":""}],"listId":8,"dateRanges":[{"_id":"6153507203385c0016b815b3","startDate":-1400,"endDate":-800}],"troopOptions":[{"_id":"6153519e03385c0016b84efa","min":1,"max":2,"dateRanges":[],"troopEntries":[{"_id":"6153519e03385c0016b84efb","troopTypeCode":"CHT","dismountTypeCode":null,"note":null}],"description":"2-horse chariots","note":"","core":"","battleCardEntries":[]},{"_id":"6153519e03385c0016b84efc","min":14,"max":22,"dateRanges":[],"troopEntries":[{"_id":"6153519e03385c0016b84efd","troopTypeCode":"BLV","dismountTypeCode":null,"note":null}],"description":"Bowmen","note":"","core":"all","battleCardEntries":[]}],"troopEntriesForGeneral":[{"_id":"6153519e03385c0016b84efe","troopEntries":[{"_id":"6153519e03385c0016b84eff","troopTypeCode":"CHT","dismountTypeCode":null,"note":null}]}],"allyOptions":[{"_id":"6153519e03385c0016b84f00","dateRange":null,"note":null,"allyEntries":[{"_id":"6153519e03385c0016b84f01","name":"Zagros Highlander allies","allyArmyList":"6153518d03385c0016b83529"}]}],"battleCardEntries":[{"_id":"6153519e03385c0016b84f02","min":null,"max":null,"battleCardCode":"PT","note":"pack donkeys"}],"showTroopOptionDescriptions":true,"status":"Revised","id":"5fb1b9d9e1af06001770930d"}]

=== marcpawl/Triumph_TTS/fake_meshwesh/armyLists/5fb1b9f6e1af06001770a490.enemyArmy.json
[{"keywords":["Maluche"],"derivedData":{"listStartDate":1461,"listEndDate":1552,"extendedName":"Araucanian  1461 to 1552 AD"},"sortId":365,"sublistId":"b","name":"Araucanian","invasionRatings":[{"_id":"6153508f03385c0016b82707","value":0,"note":null}],"maneuverRatings":[{"_id":"6153508f03385c0016b82708","value":1,"note":null}],"homeTopographies":[{"values":["Arable"],"_id":"6153508f03385c0016b82709","note":""}],"listId":355,"dateRanges":[{"_id":"6153508f03385c0016b8270a","startDate":1461,"endDate":1552}],"troopOptions":[{"_id":"615351b703385c0016b88f0f","min":8,"max":16,"dateRanges":[],"troopEntries":[{"_id":"615351b703385c0016b88f10","troopTypeCode":"LSP","dismountTypeCode":null,"note":null}],"description":"Tribesmen armed with long spears","note":"","core":"all","battleCardEntries":[]},{"_id":"615351b703385c0016b88f11","min":0,"max":8,"dateRanges":[],"troopEntries":[{"_id":"615351b703385c0016b88f12","troopTypeCode":"SKM","dismountTypeCode":null,"note":null}],"description":"Skirmishing bowmen","note":"","core":"","battleCardEntries":[]},{"_id":"615351b703385c0016b88f13","min":0,"max":2,"dateRanges":[],"troopEntries":[{"_id":"615351b703385c0016b88f14","troopTypeCode":"SKM","dismountTypeCode":null,"note":null}],"description":"Skirmishing slingers","note":"","core":"","battleCardEntries":[]}],"troopEntriesForGeneral":[{"_id":"615351b703385c0016b88f15","troopEntries":[{"_id":"615351b703385c0016b88f16","troopTypeCode":"LSP","dismountTypeCode":null,"note":null}]}],"allyOptions":[],"battleCardEntries":[],"showTroopOptionDescriptions":true,"status":"Revised","id":"5fb1b9f6e1af06001770a490"},{"keywords":[],"derivedData":{"listStartDate":1438,"listEndDate":1534,"extendedName":"Inca  1438 to 1534 AD"},"sortId":364,"sublistId":"a","name":"Inca","invasionRatings":[{"_id":"6153508f03385c0016b826f4","value":2,"note":null}],"maneuverRatings":[{"_id":"6153508f03385c0016b826f5","value":3,"note":"1438-1469 AD"},{"_id":"6153508f03385c0016b826f6","value":2,"note":"1470-1534 AD"}],"homeTopographies":[{"values":["Hilly"," Dry"],"_id":"6153508f03385c0016b826f7","note":""}],"listId":354,"dateRanges":[{"_id":"6153508f03385c0016b826f8","startDate":1438,"endDate":1534}],"troopOptions":[{"_id":"615351b703385c0016b88ee4","min":1,"max":1,"dateRanges":[],"troopEntries":[{"_id":"615351b703385c0016b88ee5","troopTypeCode":"RDR","dismountTypeCode":null,"note":null}],"description":"Inca noble bodyguard","note":"","core":"all","battleCardEntries":[]},{"_id":"615351b703385c0016b88ee6","min":3,"max":10,"dateRanges":[],"troopEntries":[{"_id":"615351b703385c0016b88ee7","troopTypeCode":"LFT","dismountTypeCode":null,"note":null}],"description":"Inca Huaminca regulars","note":"","core":"all","battleCardEntries":[]},{"_id":"615351b703385c0016b88ee8","min":4,"max":8,"dateRanges":[],"troopEntries":[{"_id":"615351b703385c0016b88ee9","troopTypeCode":"SKM","dismountTypeCode":null,"note":null}],"description":"Skirmishing slingers","note":"","core":"","battleCardEntries":[]},{"_id":"615351b703385c0016b88eea","min":2,"max":12,"dateRanges":[{"_id":"615351b703385c0016b88eeb","startDate":1469,"endDate":1534}],"troopEntries":[{"_id":"615351b703385c0016b88eec","troopTypeCode":"RBL","dismountTypeCode":null,"note":null}],"description":"Quechua and Aymara military mita","note":"","core":"","battleCardEntries":[]},{"_id":"615351b703385c0016b88eed","min":0,"max":1,"dateRanges":[{"_id":"615351b703385c0016b88eee","startDate":1476,"endDate":1534}],"troopEntries":[{"_id":"615351b703385c0016b88eef","troopTypeCode":"RDR","dismountTypeCode":null,"note":null}],"description":"Coastal Peruvian nobles","note":"","core":"all","battleCardEntries":[]}],"troopEntriesForGeneral":[{"_id":"615351b703385c0016b88ef0","troopEntries":[{"_id":"615351b703385c0016b88ef1","troopTypeCode":"RDR","dismountTypeCode":null,"note":null}]}],"allyOptions":[{"_id":"615351b703385c0016b88ef2","dateRange":{"_id":"615351b703385c0016b88ef3","startDate":1438,"endDate":1468},"note":null,"allyEntries":[{"_id":"615351b703385c0016b88ef4","name":"Quechua or Aymara allies","allyArmyList":"6153519d03385c0016b84d09"}]},{"_id":"615351b703385c0016b88ef5","dateRange":{"_id":"615351b703385c0016b88ef6","startDate":1440,"endDate":1462},"note":null,"allyEntries":[{"_id":"615351b703385c0016b88ef7","name":"Chanca allies","allyArmyList":"6153519d03385c0016b84d03"}]},{"_id":"615351b703385c0016b88ef8","dateRange":{"_id":"615351b703385c0016b88ef9","startDate":1469,"endDate":1475},"note":null,"allyEntries":[{"_id":"615351b703385c0016b88efa","name":"Peruvian coastal allies","allyArmyList":"6153519d03385c0016b84cff"}]}],"battleCardEntries":[{"_id":"615351b703385c0016b88efb","min":null,"max":null,"battleCardCode":"PT","note":"porters or pack llamas"}],"showTroopOptionDescriptions":true,"status":"Revised","id":"5fb1b9f6e1af06001770a47d"},{"keywords":[],"derivedData":{"listStartDate":1461,"listEndDate":1552,"extendedName":"Mapuche  1461 to 1552 AD"},"sortId":365,"sublistId":"a","name":"Mapuche","invasionRatings":[{"_id":"6153508f03385c0016b82701","value":0,"note":null}],"maneuverRatings":[{"_id":"6153508f03385c0016b82702","value":1,"note":null}],"homeTopographies":[{"values":["Arable"],"_id":"6153508f03385c0016b82703","note":""}],"listId":355,"dateRanges":[{"_id":"6153508f03385c0016b82704","startDate":1461,"endDate":1552}],"troopOptions":[{"_id":"615351b703385c0016b88f07","min":8,"max":16,"dateRanges":[],"troopEntries":[{"_id":"615351b703385c0016b88f08","troopTypeCode":"LFT","dismountTypeCode":null,"note":null}],"description":"Tribesmen","note":"","core":"all","battleCardEntries":[]},{"_id":"615351b703385c0016b88f09","min":0,"max":8,"dateRanges":[],"troopEntries":[{"_id":"615351b703385c0016b88f0a","troopTypeCode":"ARC","dismountTypeCode":null,"note":null}],"description":"Bowmen","note":"","core":"","battleCardEntries":[]},{"_id":"615351b703385c0016b88f0b","min":0,"max":2,"dateRanges":[],"troopEntries":[{"_id":"615351b703385c0016b88f0c","troopTypeCode":"SKM","dismountTypeCode":null,"note":null}],"description":"Skirmishing slingers","note":"","core":"","battleCardEntries":[]}],"troopEntriesForGeneral":[{"_id":"615351b703385c0016b88f0d","troopEntries":[{"_id":"615351b703385c0016b88f0e","troopTypeCode":"LFT","dismountTypeCode":null,"note":null}]}],"allyOptions":[],"battleCardEntries":[],"showTroopOptionDescriptions":true,"status":"Revised","id":"5fb1b9f6e1af06001770a48a"}]
