=== marcpawl/Triumph_TTS/fake_meshwesh/json_schemas/associatedArmyLists.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "associatedArmyLists",
  "description": "Meshwesh associatedArmyLists",
  "$id": "https://github.com/marcpawl/Triumph_TTS.git/$associatedArmyLists",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "keywords": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "derivedData": {
        "type": "object",
        "properties": {
          "listStartDate": {
            "type": "integer"
          },
          "listEndDate": {
            "type": "integer"
          },
          "extendedName": {
            "type": "string"
          }
        },
        "required": [
          "extendedName",
          "listEndDate",
          "listStartDate"
        ]
      },
      "sortId": {
        "type": "number"
      },
      "sublistId": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "invasionRatings": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "value": {
              "type": "integer"
            },
            "note": {
              "type": [
                "null",
                "string"
              ]
            }
          },
          "required": [
            "_id",
            "note",
            "value"
          ]
        }
      },
      "maneuverRatings": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "value": {
              "type": "integer"
            },
            "note": {
              "type": [
                "null",
                "string"
              ]
            }
          },
          "required": [
            "_id",
            "note",
            "value"
          ]
        }
      },
      "homeTopographies": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "values": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "_id": {
              "type": "string"
            },
            "note": {
              "type": "string"
            }
          },
          "required": [
            "_id",
            "note",
            "values"
          ]
        }
      },
      "listId": {
        "type": "number"
      },
      "dateRanges": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "startDate": {
              "type": "integer"
            },
            "endDate": {
              "type": "integer"
            }
          },
          "required": [
            "_id",
            "endDate",
            "startDate"
          ]
        }
      },
      "troopOptions": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "min": {
              "type": "integer"
            },
            "max": {
              "type": "integer"
            },
            "dateRanges": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "_id": {
                    "type": "string"
                  },
                  "startDate": {
                    "type": "integer"
                  },
                  "endDate": {
                    "type": "integer"
                  }
                },
                "required": [
                  "_id",
                  "endDate",
                  "startDate"
                ]
              }
            },
            "troopEntries": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "_id": {
                    "type": "string"
                  },
                  "troopTypeCode": {
                    "type": "string"
                  },
                  "dismountTypeCode": {
                    "type": "null"
                  },
                  "note": {
                    "type": [
                      "null",
                      "string"
                    ]
                  }
                },
                "required": [
                  "_id",
                  "dismountTypeCode",
                  "note",
                  "troopTypeCode"
                ]
              }
            },
            "description": {
              "type": "string"
            },
            "note": {
              "type": "string"
            },
            "core": {
              "type": "string"
            },
            "battleCardEntries": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "_id": {
                    "type": "string"
                  },
                  "min": {
                    "type": [
                      "integer",
                      "null"
                    ]
                  },
                  "max": {
                    "type": [
                      "integer",
                      "null"
                    ]
                  },
                  "battleCardCode": {
                    "type": "string"
                  },
                  "note": {
                    "type": [
                      "null",
                      "string"
                    ]
                  }
                },
                "required": [
                  "_id",
                  "battleCardCode",
                  "max",
                  "min",
                  "note"
                ]
              }
            }
          },
          "required": [
            "_id",
            "battleCardEntries",
            "core",
            "dateRanges",
            "description",
            "max",
            "min",
            "note",
            "troopEntries"
          ]
        }
      },
      "troopEntriesForGeneral": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "troopEntries": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "_id": {
                    "type": "string"
                  },
                  "troopTypeCode": {
                    "type": "string"
                  },
                  "dismountTypeCode": {
                    "type": "null"
                  },
                  "note": {
                    "type": [
                      "null",
                      "string"
                    ]
                  }
                },
                "required": [
                  "_id",
                  "dismountTypeCode",
                  "note",
                  "troopTypeCode"
                ]
              }
            }
          },
          "required": [
            "_id",
            "troopEntries"
          ]
        }
      },
      "allyOptions": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "dateRange": {
              "anyOf": [
                {
                  "type": "null"
                },
                {
                  "type": "object",
                  "properties": {
                    "_id": {
                      "type": "string"
                    },
                    "startDate": {
                      "type": "integer"
                    },
                    "endDate": {
                      "type": "integer"
                    }
                  },
                  "required": [
                    "_id",
                    "endDate",
                    "startDate"
                  ]
                }
              ]
            },
            "note": {
              "type": "null"
            },
            "allyEntries": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "_id": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "allyArmyList": {
                    "type": "string"
                  }
                },
                "required": [
                  "_id",
                  "allyArmyList",
                  "name"
                ]
              }
            }
          },
          "required": [
            "_id",
            "allyEntries",
            "dateRange",
            "note"
          ]
        }
      },
      "battleCardEntries": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "min": {
              "type": [
                "integer",
                "null"
              ]
            },
            "max": {
              "type": [
                "integer",
                "null"
              ]
            },
            "battleCardCode": {
              "type": "string"
            },
            "note": {
              "type": [
                "null",
                "string"
              ]
            }
          },
          "required": [
            "_id",
            "battleCardCode",
            "note"
          ]
        }
      },
      "showTroopOptionDescriptions": {
        "type": "boolean"
      },
      "status": {
        "type": "string"
      },
      "id": {
        "type": "string"
      }
    },
    "required": [
      "allyOptions",
      "battleCardEntries",
      "dateRanges",
      "derivedData",
      "homeTopographies",
      "id",
      "invasionRatings",
      "keywords",
      "listId",
      "maneuverRatings",
      "name",
      "showTroopOptionDescriptions",
      "sortId",
      "status",
      "sublistId",
      "troopEntriesForGeneral",
      "troopOptions"
    ]
  }
}

=== marcpawl/Triumph_TTS/fake_meshwesh/armyLists/5fb1b9dbe1af0600177094cb.associatedArmyLists.json
[{"keywords":["Italy"],"derivedData":{"listStartDate":-650,"listEndDate":-400,"extendedName":"Iron Age Italian  650 to 400 BC"},"sortId":51,"sublistId":"a","name":"Iron Age Italian","invasionRatings":[{"_id":"6153507403385c0016b81767","value":2,"note":null}],"maneuverRatings":[{"_id":"6153507403385c0016b81768","value":1,"note":"Etruscans"},{"_id":"6153507403385c0016b81769","value":0,"note":"All others"}],"homeTopographies":[{"values":["Arable"],"_id":"6153507403385c0016b8176a","note":""}],"listId":51,"dateRanges":[{"_id":"6153507403385c0016b8176b","startDate":-650,"endDate":-400}],"troopOptions":[{"_id":"615351a103385c0016b8553a","min":1,"max":2,"dateRanges":[],"troopEntries":[{"_id":"615351a103385c0016b8553b","troopTypeCode":"JCV","dismountTypeCode":null,"note":null}],"description":"Horsemen","note":"","core":"","battleCardEntries":[]},{"_id":"615351a103385c0016b8553c","min":6,"max":14,"dateRanges":[{"_id":"615351a103385c0016b8553d","startDate":0,"endDate":0}],"troopEntries":[{"_id":"615351a103385c0016b8553e","troopTypeCode":"HFT","dismountTypeCode":null,"note":null}],"description":"Hoplites and spearmen","note":"","core":"all","battleCardEntries":[]},{"_id":"615351a103385c0016b8553f","min":1,"max":3,"dateRanges":[],"troopEntries":[{"_id":"615351a103385c0016b85540","troopTypeCode":"RBL","dismountTypeCode":null,"note":null}],"description":"Javelinmen","note":"","core":"","battleCardEntries":[]},{"_id":"615351a103385c0016b85541","min":0,"max":2,"dateRanges":[],"troopEntries":[{"_id":"615351a103385c0016b85542","troopTypeCode":"SKM","dismountTypeCode":null,"note":null}],"description":"Skirmishing bowmen and slingers","note":"","core":"","battleCardEntries":[]}],"troopEntriesForGeneral":[{"_id":"615351a103385c0016b85543","troopEntries":[{"_id":"615351a103385c0016b85544","troopTypeCode":"JCV","dismountTypeCode":null,"note":null}]}],"allyOptions":[{"_id":"615351a103385c0016b85545","dateRange":{"_id":"615351a103385c0016b85546","startDate":-505,"endDate":-400},"note":null,"allyEntries":[{"_id":"615351a103385c0016b85547","name":"Latin Italiot allies","allyArmyList":"6153518f03385c0016b837c2"}]},{"_id":"615351a103385c0016b85548","dateRange":{"_id":"615351a103385c0016b85549","startDate":-505,"endDate":-400},"note":null,"allyEntries":[{"_id":"615351a103385c0016b8554a","name":"Latin Volsci allies","allyArmyList":"6153518f03385c0016b83765"}]}],"battleCardEntries":[],"showTroopOptionDescriptions":true,"status":"Revised","id":"5fb1b9dbe1af0600177094c4"},{"keywords":["Roman","Italy"],"derivedData":{"listStartDate":-399,"listEndDate":-338,"extendedName":"Latin  399 to 338 BC"},"sortId":51,"sublistId":"c","name":"Latin","invasionRatings":[{"_id":"6153507403385c0016b81774","value":2,"note":null}],"maneuverRatings":[{"_id":"6153507403385c0016b81775","value":2,"note":null}],"homeTopographies":[{"values":["Arable"],"_id":"6153507403385c0016b81776","note":""}],"listId":51,"dateRanges":[{"_id":"6153507403385c0016b81777","startDate":-399,"endDate":-338}],"troopOptions":[{"_id":"615351a103385c0016b85559","min":1,"max":2,"dateRanges":[],"troopEntries":[{"_id":"615351a103385c0016b8555a","troopTypeCode":"JCV","dismountTypeCode":null,"note":null}],"description":"Horsemen","note":"","core":"","battleCardEntries":[]},{"_id":"615351a103385c0016b8555b","min":2,"max":3,"dateRanges":[{"_id":"615351a103385c0016b8555c","startDate":0,"endDate":0}],"troopEntries":[{"_id":"615351a103385c0016b8555d","troopTypeCode":"EFT","dismountTypeCode":null,"note":null}],"description":"Triarii","note":"","core":"all","battleCardEntries":[{"_id":"615351a103385c0016b8555e","min":null,"max":null,"battleCardCode":"HL","note":null}]},{"_id":"615351a103385c0016b8555f","min":6,"max":12,"dateRanges":[{"_id":"615351a103385c0016b85560","startDate":0,"endDate":0}],"troopEntries":[{"_id":"615351a103385c0016b85561","troopTypeCode":"HFT","dismountTypeCode":null,"note":null}],"description":"Hastati, Principes","note":"","core":"all","battleCardEntries":[]},{"_id":"615351a103385c0016b85562","min":2,"max":3,"dateRanges":[{"_id":"615351a103385c0016b85563","startDate":0,"endDate":0}],"troopEntries":[{"_id":"615351a103385c0016b85564","troopTypeCode":"RBL","dismountTypeCode":null,"note":null}],"description":"Leves","note":"","core":"","battleCardEntries":[]},{"_id":"615351a103385c0016b85565","min":0,"max":2,"dateRanges":[],"troopEntries":[{"_id":"615351a103385c0016b85566","troopTypeCode":"SKM","dismountTypeCode":null,"note":null}],"description":"Skirmishing bowmen and slingers","note":"","core":"","battleCardEntries":[]}],"troopEntriesForGeneral":[{"_id":"615351a103385c0016b85567","troopEntries":[{"_id":"615351a103385c0016b85568","troopTypeCode":"JCV","dismountTypeCode":null,"note":null}]}],"allyOptions":[{"_id":"615351a103385c0016b85569","dateRange":null,"note":null,"allyEntries":[{"_id":"615351a103385c0016b8556a","name":"Campanian allies","allyArmyList":"6153519003385c0016b83835"}]},{"_id":"615351a103385c0016b8556b","dateRange":null,"note":null,"allyEntries":[{"_id":"615351a103385c0016b8556c","name":"Aurunci, Volsci, and/or Sidicini allies","allyArmyList":"6153518f03385c0016b83765"}]},{"_id":"615351a103385c0016b8556d","dateRange":null,"note":null,"allyEntries":[{"_id":"615351a103385c0016b8556e","name":"Syracusan allies","allyArmyList":"6153519003385c0016b83871"}]},{"_id":"615351a103385c0016b8556f","dateRange":{"_id":"615351a103385c0016b85570","startDate":-360,"endDate":-360},"note":null,"allyEntries":[{"_id":"615351a103385c0016b85571","name":"Gallic allies","allyArmyList":"6153519003385c0016b838dc"}]}],"battleCardEntries":[],"showTroopOptionDescriptions":true,"status":"Revised","id":"5fb1b9dbe1af0600177094d1"}]

=== marcpawl/Triumph_TTS/fake_meshwesh/armyLists/5fb1b9f6e1af06001770a458.associatedArmyLists.json
[{"keywords":["Polynesian"],"derivedData":{"listStartDate":1320,"listEndDate":1785,"extendedName":"Maori  1320 to 1785 AD"},"sortId":360,"sublistId":"a","name":"Maori","invasionRatings":[{"_id":"6153508f03385c0016b826be","value":1,"note":null}],"maneuverRatings":[{"_id":"6153508f03385c0016b826bf","value":0,"note":null}],"homeTopographies":[{"values":["Forest"],"_id":"6153508f03385c0016b826c0","note":""}],"listId":351,"dateRanges":[{"_id":"6153508f03385c0016b826c1","startDate":1320,"endDate":1785}],"troopOptions":[{"_id":"615351b603385c0016b88e98","min":11,"max":12,"dateRanges":[],"troopEntries":[{"_id":"615351b603385c0016b88e99","troopTypeCode":"RDR","dismountTypeCode":null,"note":null}],"description":"Tribesmen","note":"","core":"all","battleCardEntries":[]}],"troopEntriesForGeneral":[{"_id":"615351b603385c0016b88e9a","troopEntries":[{"_id":"615351b603385c0016b88e9b","troopTypeCode":"RDR","dismountTypeCode":null,"note":null}]}],"allyOptions":[],"battleCardEntries":[{"_id":"615351b603385c0016b88e9c","min":null,"max":null,"battleCardCode":"FC","note":"Log palisade"}],"showTroopOptionDescriptions":true,"status":"Revised","id":"5fb1b9f6e1af06001770a446"},{"keywords":["Polynesian"],"derivedData":{"listStartDate":700,"listEndDate":1785,"extendedName":"Outer Polynesian  700 to 1785 AD"},"sortId":360,"sublistId":"b","name":"Outer Polynesian","invasionRatings":[{"_id":"6153508f03385c0016b826c4","value":1,"note":null}],"maneuverRatings":[{"_id":"6153508f03385c0016b826c5","value":0,"note":null}],"homeTopographies":[{"values":["Forest"],"_id":"6153508f03385c0016b826c6","note":""}],"listId":351,"dateRanges":[{"_id":"6153508f03385c0016b826c7","startDate":700,"endDate":1785}],"troopOptions":[{"_id":"615351b603385c0016b88e9d","min":10,"max":11,"dateRanges":[],"troopEntries":[{"_id":"615351b603385c0016b88e9e","troopTypeCode":"RDR","dismountTypeCode":null,"note":null}],"description":"Tribesmen","note":"","core":"all","battleCardEntries":[]},{"_id":"615351b603385c0016b88e9f","min":1,"max":2,"dateRanges":[],"troopEntries":[{"_id":"615351b603385c0016b88ea0","troopTypeCode":"SKM","dismountTypeCode":null,"note":null}],"description":"Skirmishing slingers","note":"","core":"","battleCardEntries":[]}],"troopEntriesForGeneral":[{"_id":"615351b603385c0016b88ea1","troopEntries":[{"_id":"615351b603385c0016b88ea2","troopTypeCode":"RDR","dismountTypeCode":null,"note":null}]}],"allyOptions":[],"battleCardEntries":[{"_id":"615351b603385c0016b88ea3","min":null,"max":null,"battleCardCode":"FC","note":"Log palisade"}],"showTroopOptionDescriptions":true,"status":"Revised","id":"5fb1b9f6e1af06001770a44c"},{"keywords":["Polynesian"],"derivedData":{"listStartDate":-800,"listEndDate":1785,"extendedName":"Central Polynesian  800 BC to 1785 AD"},"sortId":360,"sublistId":"c","name":"Central Polynesian","invasionRatings":[{"_id":"6153508f03385c0016b826ca","value":1,"note":null}],"maneuverRatings":[{"_id":"6153508f03385c0016b826cb","value":0,"note":null}],"homeTopographies":[{"values":["Forest"],"_id":"6153508f03385c0016b826cc","note":""}],"listId":351,"dateRanges":[{"_id":"6153508f03385c0016b826cd","startDate":-800,"endDate":1785}],"troopOptions":[{"_id":"615351b603385c0016b88ea4","min":14,"max":15,"dateRanges":[],"troopEntries":[{"_id":"615351b603385c0016b88ea5","troopTypeCode":"WBD","dismountTypeCode":null,"note":null}],"description":"Fierce tribesmen","note":"","core":"all","battleCardEntries":[]},{"_id":"615351b603385c0016b88ea6","min":1,"max":2,"dateRanges":[],"troopEntries":[{"_id":"615351b603385c0016b88ea7","troopTypeCode":"SKM","dismountTypeCode":null,"note":null}],"description":"Skirmishing bowmen and slingers","note":"","core":"","battleCardEntries":[]}],"troopEntriesForGeneral":[{"_id":"615351b603385c0016b88ea8","troopEntries":[{"_id":"615351b603385c0016b88ea9","troopTypeCode":"WBD","dismountTypeCode":null,"note":null}]}],"allyOptions":[],"battleCardEntries":[{"_id":"615351b603385c0016b88eaa","min":null,"max":null,"battleCardCode":"FC","note":"Log palisade"}],"showTroopOptionDescriptions":true,"status":"Revised","id":"5fb1b9f6e1af06001770a452"},{"keywords":["Polynesian"],"derivedData":{"listStartDate":-1200,"listEndDate":1785,"extendedName":"Melanesian  1200 BC to 1785 AD"},"sortId":360,"sublistId":"e","name":"Melanesian","invasionRatings":[{"_id":"6153508f03385c0016b826d6","value":1,"note":null}],"maneuverRatings":[{"_id":"6153508f03385c0016b826d7","value":0,"note":null}],"homeTopographies":[{"values":["Forest"],"_id":"6153508f03385c0016b826d8","note":""}],"listId":351,"dateRanges":[{"_id":"6153508f03385c0016b826d9","startDate":-1200,"endDate":1785}],"troopOptions":[{"_id":"615351b603385c0016b88eb8","min":13,"max":15,"dateRanges":[],"troopEntries":[{"_id":"615351b603385c0016b88eb9","troopTypeCode":"LFT","dismountTypeCode":null,"note":null}],"description":"Tribesmen","note":"","core":"all","battleCardEntries":[]},{"_id":"615351b603385c0016b88eba","min":1,"max":3,"dateRanges":[],"troopEntries":[{"_id":"615351b603385c0016b88ebb","troopTypeCode":"SKM","dismountTypeCode":null,"note":null}],"description":"Skirmishing bowmen and slingers","note":"","core":"","battleCardEntries":[]}],"troopEntriesForGeneral":[{"_id":"615351b603385c0016b88ebc","troopEntries":[{"_id":"615351b603385c0016b88ebd","troopTypeCode":"LFT","dismountTypeCode":null,"note":null}]}],"allyOptions":[],"battleCardEntries":[{"_id":"615351b603385c0016b88ebe","min":null,"max":null,"battleCardCode":"FC","note":"Log palisade"}],"showTroopOptionDescriptions":true,"status":"Revised","id":"5fb1b9f6e1af06001770a45e"}]
